
openapi: 3.0.0
info:
  title: Twin API (Firebase Auth)
  version: 1.0.0
servers:
  - url: https://GATEWAY_HOSTNAME

components:
  securitySchemes:
    firebase:
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-google-issuer: "https://securetoken.google.com/PROJECT_ID"
      x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com"
      x-google-audiences: "PROJECT_ID"

security:
  - firebase: []

paths:
  /query:
    post:
      summary: RAG query (requires Firebase ID token)
      security:
        - firebase: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question: { type: string }
                k: { type: integer }
      responses:
        "200":
          description: OK

x-google-backend:
  address: https://CLOUD_RUN_URL
  path_translation: APPEND_PATH_TO_ADDRESS
  jwt_audience: https://CLOUD_RUN_URL
