
name: flutter_twin
description: Living Twin mobile app with offline capabilities
publish_to: "none"
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.3
  connectivity_plus: ^5.0.2
  uuid: ^4.2.1
  intl: ^0.19.0
  provider: ^6.1.1
  # Speech packages - hardware accelerated
  speech_to_text: ^6.6.0
  flutter_tts: ^4.0.2
  permission_handler: ^11.3.1
  # Audio processing and feedback
  audio_waveforms: ^1.0.5
  just_audio: ^0.9.37
  # Voice activity detection - using noise_meter instead
  noise_meter: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
